import {
  RiAccountCircleFill,
  RiAddCircleLine,
  RiAddLine,
  RiArrowDownSFill,
  RiArrowRightCircleLine,
  RiArrowRightSLine,
  RiBook2Fill,
  RiCheckLine,
  RiCoinsFill,
  RiEqualizerFill,
  RiFacebookBoxFill,
  RiFacebookLine,
  RiFlashlightFill,
  RiGoogleLine,
  RiHomeFill,
  RiInstagramLine,
  RiListUnordered,
  RiMailLine,
  RiNotification2Fill,
  RiSearchLine,
  RiSettings2Fill,
  RiSubtractLine,
  RiTwitterLine,
  RiYoutubeLine,
} from 'react-icons/ri';

export const Icons = {
  ArrowDown: RiArrowDownSFill,
  User: RiAccountCircleFill,
  Search: RiSearchLine,
  Twitter: RiTwitterLine,
  Facebook: RiFacebookLine,
  FacebookBox: RiFacebookBoxFill,
  YouTube: RiYoutubeLine,
  Instagram: RiInstagramLine,
  Google: RiGoogleLine,
  Book: RiBook2Fill,
  Premium: RiFlashlightFill,
  Home: RiHomeFill,
  Notification: RiNotification2Fill,
  EqualizeFill: RiEqualizerFill,
  Dollar: RiCoinsFill,
  Add: RiAddLine,
  AddCircle: RiAddCircleLine,
  ArrowLeft: RiArrowRightSLine,
  ArrowRightCircle: RiArrowRightCircleLine,
  Check: RiCheckLine,
  Lists: RiListUnordered,
  Mail: RiMailLine,
  Setting: RiSettings2Fill,
  Minus: RiSubtractLine,
};
